application.env: LOCAL

server:
  port: 8080

############################# SPRING CONFIG #############################
spring:
  application.name: cdc-debezium-engine
  kafka:
    bootstrap.servers: localhost:29092
    topic-avro: LOCAL_STUDENT_DATA_AVRO
    topic-avro-generic: LOCAL_GENERIC_DATA_AVRO
    topic-json: LOCAL_STUDENT_DATA_JSON
    topic-student-avro: LOCAL_STUDENT_AVRO
    schema.registry:
#        url: http://127.0.0.1:8081/
        url: http://localhost:8081/

##################### ACTUATOR CONFIG FOR APPLICATION HEALTH CHECK #######################
management.endpoints.web.exposure.include: health,metrics

management:
  endpoint:
    health:
      probes:
        enabled: 'true'
      show-details: always

############################## APPLICATION CONFIGS #################################
config:
  ############################ DEBEZIUM ENGINE SETTINGS ############################
  debezium:
    ### GENERAL SETTINGS ###
    engine.name: debezium-pg-connector
    topic.prefix: KGKDemo
    heartbeat.interval.ms: 30000

    ### OFFSET SETTINGS - AS A KAFKA TOPIC ###
    kafka:
      offset.storage: org.apache.kafka.connect.storage.KafkaOffsetBackingStore
      offset.storage.partitions: 1
      offset.storage.topic: DBZ_WAL_RECORDS
      offset.storage.replication.factor: 1
      offset.flush.interval.ms: 10000

    ### DATABASE SETTINGS ###
    database:
      hostname: localhost
      port: 5432
      user: debezium_user4
      password: kgk123
      dbname: postgres

      connector.class: io.debezium.connector.postgresql.PostgresConnector
      plugin.name: pgoutput
      snapshot.mode: never
      slot.name: dbz_slot
      publication.name: dbz_publication
      publication.auto.create.mode: disabled

      ### COMMON TABLES ###
      schema.include.list: demo
      table.include.list: demo.students, demo.address
      #column.include.list:
      column.exclude.list: demo.students.created_date
      common.tables.slot_drop_on_stop: true
      decimal.handling.mode: double


    ### MESSAGE SETTINGS ###
    converter.schemas.enable: false

  application:
    enable-rest-api : false
    enable-debezium-cdc-engine: false
    enable-debezium-cdc-engine-avro: true
    enable-debezium-cdc-engine-json: false

############################ END ############################