/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kgk.debezium.engine.demo.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ChangedRecordV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6504949216150782186L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChangedRecordV2\",\"namespace\":\"com.kgk.debezium.engine.demo.dto\",\"fields\":[{\"name\":\"source\",\"type\":{\"type\":\"record\",\"name\":\"Source\",\"fields\":[{\"name\":\"db\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"schema\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"table\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lsn\",\"type\":\"long\"}]}},{\"name\":\"operation\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"tsMs\",\"type\":\"long\"},{\"name\":\"data\",\"type\":{\"type\":\"record\",\"name\":\"Student\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"address_id\",\"type\":[\"int\",\"null\"]},{\"name\":\"department_id\",\"type\":[\"int\",\"null\"]},{\"name\":\"department\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"is_active\",\"type\":\"boolean\",\"default\":false},{\"name\":\"created_date\",\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}]},{\"name\":\"modified_date\",\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<ChangedRecordV2> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ChangedRecordV2> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ChangedRecordV2> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ChangedRecordV2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ChangedRecordV2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ChangedRecordV2 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ChangedRecordV2 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ChangedRecordV2 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ChangedRecordV2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.kgk.debezium.engine.demo.dto.Source source;
  private java.lang.String operation;
  private long tsMs;
  private com.kgk.debezium.engine.demo.dto.Student data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ChangedRecordV2() {}

  /**
   * All-args constructor.
   * @param source The new value for source
   * @param operation The new value for operation
   * @param tsMs The new value for tsMs
   * @param data The new value for data
   */
  public ChangedRecordV2(com.kgk.debezium.engine.demo.dto.Source source, java.lang.String operation, java.lang.Long tsMs, com.kgk.debezium.engine.demo.dto.Student data) {
    this.source = source;
    this.operation = operation;
    this.tsMs = tsMs;
    this.data = data;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return source;
    case 1: return operation;
    case 2: return tsMs;
    case 3: return data;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: source = (com.kgk.debezium.engine.demo.dto.Source)value$; break;
    case 1: operation = value$ != null ? value$.toString() : null; break;
    case 2: tsMs = (java.lang.Long)value$; break;
    case 3: data = (com.kgk.debezium.engine.demo.dto.Student)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public com.kgk.debezium.engine.demo.dto.Source getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(com.kgk.debezium.engine.demo.dto.Source value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'operation' field.
   * @return The value of the 'operation' field.
   */
  public java.lang.String getOperation() {
    return operation;
  }


  /**
   * Sets the value of the 'operation' field.
   * @param value the value to set.
   */
  public void setOperation(java.lang.String value) {
    this.operation = value;
  }

  /**
   * Gets the value of the 'tsMs' field.
   * @return The value of the 'tsMs' field.
   */
  public long getTsMs() {
    return tsMs;
  }


  /**
   * Sets the value of the 'tsMs' field.
   * @param value the value to set.
   */
  public void setTsMs(long value) {
    this.tsMs = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public com.kgk.debezium.engine.demo.dto.Student getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(com.kgk.debezium.engine.demo.dto.Student value) {
    this.data = value;
  }

  /**
   * Creates a new ChangedRecordV2 RecordBuilder.
   * @return A new ChangedRecordV2 RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder newBuilder() {
    return new com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder();
  }

  /**
   * Creates a new ChangedRecordV2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ChangedRecordV2 RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder newBuilder(com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder other) {
    if (other == null) {
      return new com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder();
    } else {
      return new com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder(other);
    }
  }

  /**
   * Creates a new ChangedRecordV2 RecordBuilder by copying an existing ChangedRecordV2 instance.
   * @param other The existing instance to copy.
   * @return A new ChangedRecordV2 RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder newBuilder(com.kgk.debezium.engine.demo.dto.ChangedRecordV2 other) {
    if (other == null) {
      return new com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder();
    } else {
      return new com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder(other);
    }
  }

  /**
   * RecordBuilder for ChangedRecordV2 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChangedRecordV2>
    implements org.apache.avro.data.RecordBuilder<ChangedRecordV2> {

    private com.kgk.debezium.engine.demo.dto.Source source;
    private com.kgk.debezium.engine.demo.dto.Source.Builder sourceBuilder;
    private java.lang.String operation;
    private long tsMs;
    private com.kgk.debezium.engine.demo.dto.Student data;
    private com.kgk.debezium.engine.demo.dto.Student.Builder dataBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.source)) {
        this.source = data().deepCopy(fields()[0].schema(), other.source);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasSourceBuilder()) {
        this.sourceBuilder = com.kgk.debezium.engine.demo.dto.Source.newBuilder(other.getSourceBuilder());
      }
      if (isValidValue(fields()[1], other.operation)) {
        this.operation = data().deepCopy(fields()[1].schema(), other.operation);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.tsMs)) {
        this.tsMs = data().deepCopy(fields()[2].schema(), other.tsMs);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasDataBuilder()) {
        this.dataBuilder = com.kgk.debezium.engine.demo.dto.Student.newBuilder(other.getDataBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ChangedRecordV2 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kgk.debezium.engine.demo.dto.ChangedRecordV2 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.source)) {
        this.source = data().deepCopy(fields()[0].schema(), other.source);
        fieldSetFlags()[0] = true;
      }
      this.sourceBuilder = null;
      if (isValidValue(fields()[1], other.operation)) {
        this.operation = data().deepCopy(fields()[1].schema(), other.operation);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tsMs)) {
        this.tsMs = data().deepCopy(fields()[2].schema(), other.tsMs);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = true;
      }
      this.dataBuilder = null;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public com.kgk.debezium.engine.demo.dto.Source getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder setSource(com.kgk.debezium.engine.demo.dto.Source value) {
      validate(fields()[0], value);
      this.sourceBuilder = null;
      this.source = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'source' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kgk.debezium.engine.demo.dto.Source.Builder getSourceBuilder() {
      if (sourceBuilder == null) {
        if (hasSource()) {
          setSourceBuilder(com.kgk.debezium.engine.demo.dto.Source.newBuilder(source));
        } else {
          setSourceBuilder(com.kgk.debezium.engine.demo.dto.Source.newBuilder());
        }
      }
      return sourceBuilder;
    }

    /**
     * Sets the Builder instance for the 'source' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder setSourceBuilder(com.kgk.debezium.engine.demo.dto.Source.Builder value) {
      clearSource();
      sourceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'source' field has an active Builder instance
     * @return True if the 'source' field has an active Builder instance
     */
    public boolean hasSourceBuilder() {
      return sourceBuilder != null;
    }

    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder clearSource() {
      source = null;
      sourceBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'operation' field.
      * @return The value.
      */
    public java.lang.String getOperation() {
      return operation;
    }


    /**
      * Sets the value of the 'operation' field.
      * @param value The value of 'operation'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder setOperation(java.lang.String value) {
      validate(fields()[1], value);
      this.operation = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'operation' field has been set.
      * @return True if the 'operation' field has been set, false otherwise.
      */
    public boolean hasOperation() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'operation' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder clearOperation() {
      operation = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tsMs' field.
      * @return The value.
      */
    public long getTsMs() {
      return tsMs;
    }


    /**
      * Sets the value of the 'tsMs' field.
      * @param value The value of 'tsMs'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder setTsMs(long value) {
      validate(fields()[2], value);
      this.tsMs = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tsMs' field has been set.
      * @return True if the 'tsMs' field has been set, false otherwise.
      */
    public boolean hasTsMs() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tsMs' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder clearTsMs() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public com.kgk.debezium.engine.demo.dto.Student getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder setData(com.kgk.debezium.engine.demo.dto.Student value) {
      validate(fields()[3], value);
      this.dataBuilder = null;
      this.data = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'data' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kgk.debezium.engine.demo.dto.Student.Builder getDataBuilder() {
      if (dataBuilder == null) {
        if (hasData()) {
          setDataBuilder(com.kgk.debezium.engine.demo.dto.Student.newBuilder(data));
        } else {
          setDataBuilder(com.kgk.debezium.engine.demo.dto.Student.newBuilder());
        }
      }
      return dataBuilder;
    }

    /**
     * Sets the Builder instance for the 'data' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder setDataBuilder(com.kgk.debezium.engine.demo.dto.Student.Builder value) {
      clearData();
      dataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'data' field has an active Builder instance
     * @return True if the 'data' field has an active Builder instance
     */
    public boolean hasDataBuilder() {
      return dataBuilder != null;
    }

    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.ChangedRecordV2.Builder clearData() {
      data = null;
      dataBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ChangedRecordV2 build() {
      try {
        ChangedRecordV2 record = new ChangedRecordV2();
        if (sourceBuilder != null) {
          try {
            record.source = this.sourceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("source"));
            throw e;
          }
        } else {
          record.source = fieldSetFlags()[0] ? this.source : (com.kgk.debezium.engine.demo.dto.Source) defaultValue(fields()[0]);
        }
        record.operation = fieldSetFlags()[1] ? this.operation : (java.lang.String) defaultValue(fields()[1]);
        record.tsMs = fieldSetFlags()[2] ? this.tsMs : (java.lang.Long) defaultValue(fields()[2]);
        if (dataBuilder != null) {
          try {
            record.data = this.dataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("data"));
            throw e;
          }
        } else {
          record.data = fieldSetFlags()[3] ? this.data : (com.kgk.debezium.engine.demo.dto.Student) defaultValue(fields()[3]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ChangedRecordV2>
    WRITER$ = (org.apache.avro.io.DatumWriter<ChangedRecordV2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ChangedRecordV2>
    READER$ = (org.apache.avro.io.DatumReader<ChangedRecordV2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










