/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kgk.debezium.engine.demo.dto;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class Student extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6917057013984494623L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Student\",\"namespace\":\"com.kgk.debezium.engine.demo.dto\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"address_id\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"department_id\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"department\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"is_active\",\"type\":[{\"type\":\"boolean\",\"connect.default\":true},\"null\"],\"default\":true},{\"name\":\"created_date\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"modified_date\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Student> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Student> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Student> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Student> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Student> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Student to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Student from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Student instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Student fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private java.lang.String name;
  private java.lang.Integer address_id;
  private java.lang.Integer department_id;
  private java.lang.String department;
  private java.lang.Boolean is_active;
  private java.lang.Long created_date;
  private java.lang.Long modified_date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Student() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param address_id The new value for address_id
   * @param department_id The new value for department_id
   * @param department The new value for department
   * @param is_active The new value for is_active
   * @param created_date The new value for created_date
   * @param modified_date The new value for modified_date
   */
  public Student(java.lang.Integer id, java.lang.String name, java.lang.Integer address_id, java.lang.Integer department_id, java.lang.String department, java.lang.Boolean is_active, java.lang.Long created_date, java.lang.Long modified_date) {
    this.id = id;
    this.name = name;
    this.address_id = address_id;
    this.department_id = department_id;
    this.department = department;
    this.is_active = is_active;
    this.created_date = created_date;
    this.modified_date = modified_date;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return address_id;
    case 3: return department_id;
    case 4: return department;
    case 5: return is_active;
    case 6: return created_date;
    case 7: return modified_date;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: address_id = (java.lang.Integer)value$; break;
    case 3: department_id = (java.lang.Integer)value$; break;
    case 4: department = value$ != null ? value$.toString() : null; break;
    case 5: is_active = (java.lang.Boolean)value$; break;
    case 6: created_date = (java.lang.Long)value$; break;
    case 7: modified_date = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'address_id' field.
   * @return The value of the 'address_id' field.
   */
  public java.lang.Integer getAddressId() {
    return address_id;
  }


  /**
   * Sets the value of the 'address_id' field.
   * @param value the value to set.
   */
  public void setAddressId(java.lang.Integer value) {
    this.address_id = value;
  }

  /**
   * Gets the value of the 'department_id' field.
   * @return The value of the 'department_id' field.
   */
  public java.lang.Integer getDepartmentId() {
    return department_id;
  }


  /**
   * Sets the value of the 'department_id' field.
   * @param value the value to set.
   */
  public void setDepartmentId(java.lang.Integer value) {
    this.department_id = value;
  }

  /**
   * Gets the value of the 'department' field.
   * @return The value of the 'department' field.
   */
  public java.lang.String getDepartment() {
    return department;
  }


  /**
   * Sets the value of the 'department' field.
   * @param value the value to set.
   */
  public void setDepartment(java.lang.String value) {
    this.department = value;
  }

  /**
   * Gets the value of the 'is_active' field.
   * @return The value of the 'is_active' field.
   */
  public java.lang.Boolean getIsActive() {
    return is_active;
  }


  /**
   * Sets the value of the 'is_active' field.
   * @param value the value to set.
   */
  public void setIsActive(java.lang.Boolean value) {
    this.is_active = value;
  }

  /**
   * Gets the value of the 'created_date' field.
   * @return The value of the 'created_date' field.
   */
  public java.lang.Long getCreatedDate() {
    return created_date;
  }


  /**
   * Sets the value of the 'created_date' field.
   * @param value the value to set.
   */
  public void setCreatedDate(java.lang.Long value) {
    this.created_date = value;
  }

  /**
   * Gets the value of the 'modified_date' field.
   * @return The value of the 'modified_date' field.
   */
  public java.lang.Long getModifiedDate() {
    return modified_date;
  }


  /**
   * Sets the value of the 'modified_date' field.
   * @param value the value to set.
   */
  public void setModifiedDate(java.lang.Long value) {
    this.modified_date = value;
  }

  /**
   * Creates a new Student RecordBuilder.
   * @return A new Student RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.Student.Builder newBuilder() {
    return new com.kgk.debezium.engine.demo.dto.Student.Builder();
  }

  /**
   * Creates a new Student RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Student RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.Student.Builder newBuilder(com.kgk.debezium.engine.demo.dto.Student.Builder other) {
    if (other == null) {
      return new com.kgk.debezium.engine.demo.dto.Student.Builder();
    } else {
      return new com.kgk.debezium.engine.demo.dto.Student.Builder(other);
    }
  }

  /**
   * Creates a new Student RecordBuilder by copying an existing Student instance.
   * @param other The existing instance to copy.
   * @return A new Student RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.Student.Builder newBuilder(com.kgk.debezium.engine.demo.dto.Student other) {
    if (other == null) {
      return new com.kgk.debezium.engine.demo.dto.Student.Builder();
    } else {
      return new com.kgk.debezium.engine.demo.dto.Student.Builder(other);
    }
  }

  /**
   * RecordBuilder for Student instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Student>
    implements org.apache.avro.data.RecordBuilder<Student> {

    private int id;
    private java.lang.String name;
    private java.lang.Integer address_id;
    private java.lang.Integer department_id;
    private java.lang.String department;
    private java.lang.Boolean is_active;
    private java.lang.Long created_date;
    private java.lang.Long modified_date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kgk.debezium.engine.demo.dto.Student.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.address_id)) {
        this.address_id = data().deepCopy(fields()[2].schema(), other.address_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.department_id)) {
        this.department_id = data().deepCopy(fields()[3].schema(), other.department_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.department)) {
        this.department = data().deepCopy(fields()[4].schema(), other.department);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.is_active)) {
        this.is_active = data().deepCopy(fields()[5].schema(), other.is_active);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.created_date)) {
        this.created_date = data().deepCopy(fields()[6].schema(), other.created_date);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.modified_date)) {
        this.modified_date = data().deepCopy(fields()[7].schema(), other.modified_date);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing Student instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kgk.debezium.engine.demo.dto.Student other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.address_id)) {
        this.address_id = data().deepCopy(fields()[2].schema(), other.address_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.department_id)) {
        this.department_id = data().deepCopy(fields()[3].schema(), other.department_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.department)) {
        this.department = data().deepCopy(fields()[4].schema(), other.department);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.is_active)) {
        this.is_active = data().deepCopy(fields()[5].schema(), other.is_active);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.created_date)) {
        this.created_date = data().deepCopy(fields()[6].schema(), other.created_date);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.modified_date)) {
        this.modified_date = data().deepCopy(fields()[7].schema(), other.modified_date);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'address_id' field.
      * @return The value.
      */
    public java.lang.Integer getAddressId() {
      return address_id;
    }


    /**
      * Sets the value of the 'address_id' field.
      * @param value The value of 'address_id'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setAddressId(java.lang.Integer value) {
      validate(fields()[2], value);
      this.address_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'address_id' field has been set.
      * @return True if the 'address_id' field has been set, false otherwise.
      */
    public boolean hasAddressId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'address_id' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearAddressId() {
      address_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'department_id' field.
      * @return The value.
      */
    public java.lang.Integer getDepartmentId() {
      return department_id;
    }


    /**
      * Sets the value of the 'department_id' field.
      * @param value The value of 'department_id'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setDepartmentId(java.lang.Integer value) {
      validate(fields()[3], value);
      this.department_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'department_id' field has been set.
      * @return True if the 'department_id' field has been set, false otherwise.
      */
    public boolean hasDepartmentId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'department_id' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearDepartmentId() {
      department_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'department' field.
      * @return The value.
      */
    public java.lang.String getDepartment() {
      return department;
    }


    /**
      * Sets the value of the 'department' field.
      * @param value The value of 'department'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setDepartment(java.lang.String value) {
      validate(fields()[4], value);
      this.department = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'department' field has been set.
      * @return True if the 'department' field has been set, false otherwise.
      */
    public boolean hasDepartment() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'department' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearDepartment() {
      department = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'is_active' field.
      * @return The value.
      */
    public java.lang.Boolean getIsActive() {
      return is_active;
    }


    /**
      * Sets the value of the 'is_active' field.
      * @param value The value of 'is_active'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setIsActive(java.lang.Boolean value) {
      validate(fields()[5], value);
      this.is_active = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'is_active' field has been set.
      * @return True if the 'is_active' field has been set, false otherwise.
      */
    public boolean hasIsActive() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'is_active' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearIsActive() {
      is_active = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_date' field.
      * @return The value.
      */
    public java.lang.Long getCreatedDate() {
      return created_date;
    }


    /**
      * Sets the value of the 'created_date' field.
      * @param value The value of 'created_date'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setCreatedDate(java.lang.Long value) {
      validate(fields()[6], value);
      this.created_date = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'created_date' field has been set.
      * @return True if the 'created_date' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'created_date' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearCreatedDate() {
      created_date = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'modified_date' field.
      * @return The value.
      */
    public java.lang.Long getModifiedDate() {
      return modified_date;
    }


    /**
      * Sets the value of the 'modified_date' field.
      * @param value The value of 'modified_date'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder setModifiedDate(java.lang.Long value) {
      validate(fields()[7], value);
      this.modified_date = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'modified_date' field has been set.
      * @return True if the 'modified_date' field has been set, false otherwise.
      */
    public boolean hasModifiedDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'modified_date' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.Student.Builder clearModifiedDate() {
      modified_date = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Student build() {
      try {
        Student record = new Student();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.address_id = fieldSetFlags()[2] ? this.address_id : (java.lang.Integer) defaultValue(fields()[2]);
        record.department_id = fieldSetFlags()[3] ? this.department_id : (java.lang.Integer) defaultValue(fields()[3]);
        record.department = fieldSetFlags()[4] ? this.department : (java.lang.String) defaultValue(fields()[4]);
        record.is_active = fieldSetFlags()[5] ? this.is_active : (java.lang.Boolean) defaultValue(fields()[5]);
        record.created_date = fieldSetFlags()[6] ? this.created_date : (java.lang.Long) defaultValue(fields()[6]);
        record.modified_date = fieldSetFlags()[7] ? this.modified_date : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Student>
    WRITER$ = (org.apache.avro.io.DatumWriter<Student>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Student>
    READER$ = (org.apache.avro.io.DatumReader<Student>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.address_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.address_id);
    }

    if (this.department_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.department_id);
    }

    if (this.department == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.department);
    }

    if (this.is_active == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeBoolean(this.is_active);
    }

    if (this.created_date == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.created_date);
    }

    if (this.modified_date == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.modified_date);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.address_id = null;
      } else {
        this.address_id = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.department_id = null;
      } else {
        this.department_id = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.department = null;
      } else {
        this.department = in.readString();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.is_active = null;
      } else {
        this.is_active = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.created_date = null;
      } else {
        this.created_date = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.modified_date = null;
      } else {
        this.modified_date = in.readLong();
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.address_id = null;
          } else {
            this.address_id = in.readInt();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.department_id = null;
          } else {
            this.department_id = in.readInt();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.department = null;
          } else {
            this.department = in.readString();
          }
          break;

        case 5:
          if (in.readIndex() != 0) {
            in.readNull();
            this.is_active = null;
          } else {
            this.is_active = in.readBoolean();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.created_date = null;
          } else {
            this.created_date = in.readLong();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.modified_date = null;
          } else {
            this.modified_date = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










