/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kgk.debezium.engine.demo.dto;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class StudentChangedRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4081884667663832063L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StudentChangedRecord\",\"namespace\":\"com.kgk.debezium.engine.demo.dto\",\"fields\":[{\"name\":\"source\",\"type\":{\"type\":\"record\",\"name\":\"Source\",\"fields\":[{\"name\":\"db\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"schema\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"table\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lsn\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"ts_ms\",\"type\":\"long\"}]}},{\"name\":\"operation\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ts_ms\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"data\",\"type\":{\"type\":\"record\",\"name\":\"Student\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"address_id\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"department_id\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"department\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"is_active\",\"type\":[{\"type\":\"boolean\",\"connect.default\":true},\"null\"],\"default\":true},{\"name\":\"created_date\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"modified_date\",\"type\":[\"null\",\"long\"],\"default\":null}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StudentChangedRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StudentChangedRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StudentChangedRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StudentChangedRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StudentChangedRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StudentChangedRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StudentChangedRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StudentChangedRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StudentChangedRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.kgk.debezium.engine.demo.dto.Source source;
  private java.lang.String operation;
  private java.lang.Long ts_ms;
  private com.kgk.debezium.engine.demo.dto.Student data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StudentChangedRecord() {}

  /**
   * All-args constructor.
   * @param source The new value for source
   * @param operation The new value for operation
   * @param ts_ms The new value for ts_ms
   * @param data The new value for data
   */
  public StudentChangedRecord(com.kgk.debezium.engine.demo.dto.Source source, java.lang.String operation, java.lang.Long ts_ms, com.kgk.debezium.engine.demo.dto.Student data) {
    this.source = source;
    this.operation = operation;
    this.ts_ms = ts_ms;
    this.data = data;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return source;
    case 1: return operation;
    case 2: return ts_ms;
    case 3: return data;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: source = (com.kgk.debezium.engine.demo.dto.Source)value$; break;
    case 1: operation = value$ != null ? value$.toString() : null; break;
    case 2: ts_ms = (java.lang.Long)value$; break;
    case 3: data = (com.kgk.debezium.engine.demo.dto.Student)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public com.kgk.debezium.engine.demo.dto.Source getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(com.kgk.debezium.engine.demo.dto.Source value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'operation' field.
   * @return The value of the 'operation' field.
   */
  public java.lang.String getOperation() {
    return operation;
  }


  /**
   * Sets the value of the 'operation' field.
   * @param value the value to set.
   */
  public void setOperation(java.lang.String value) {
    this.operation = value;
  }

  /**
   * Gets the value of the 'ts_ms' field.
   * @return The value of the 'ts_ms' field.
   */
  public java.lang.Long getTsMs() {
    return ts_ms;
  }


  /**
   * Sets the value of the 'ts_ms' field.
   * @param value the value to set.
   */
  public void setTsMs(java.lang.Long value) {
    this.ts_ms = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public com.kgk.debezium.engine.demo.dto.Student getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(com.kgk.debezium.engine.demo.dto.Student value) {
    this.data = value;
  }

  /**
   * Creates a new StudentChangedRecord RecordBuilder.
   * @return A new StudentChangedRecord RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder newBuilder() {
    return new com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder();
  }

  /**
   * Creates a new StudentChangedRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StudentChangedRecord RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder newBuilder(com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder other) {
    if (other == null) {
      return new com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder();
    } else {
      return new com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder(other);
    }
  }

  /**
   * Creates a new StudentChangedRecord RecordBuilder by copying an existing StudentChangedRecord instance.
   * @param other The existing instance to copy.
   * @return A new StudentChangedRecord RecordBuilder
   */
  public static com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder newBuilder(com.kgk.debezium.engine.demo.dto.StudentChangedRecord other) {
    if (other == null) {
      return new com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder();
    } else {
      return new com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for StudentChangedRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StudentChangedRecord>
    implements org.apache.avro.data.RecordBuilder<StudentChangedRecord> {

    private com.kgk.debezium.engine.demo.dto.Source source;
    private com.kgk.debezium.engine.demo.dto.Source.Builder sourceBuilder;
    private java.lang.String operation;
    private java.lang.Long ts_ms;
    private com.kgk.debezium.engine.demo.dto.Student data;
    private com.kgk.debezium.engine.demo.dto.Student.Builder dataBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.source)) {
        this.source = data().deepCopy(fields()[0].schema(), other.source);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasSourceBuilder()) {
        this.sourceBuilder = com.kgk.debezium.engine.demo.dto.Source.newBuilder(other.getSourceBuilder());
      }
      if (isValidValue(fields()[1], other.operation)) {
        this.operation = data().deepCopy(fields()[1].schema(), other.operation);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ts_ms)) {
        this.ts_ms = data().deepCopy(fields()[2].schema(), other.ts_ms);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasDataBuilder()) {
        this.dataBuilder = com.kgk.debezium.engine.demo.dto.Student.newBuilder(other.getDataBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing StudentChangedRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kgk.debezium.engine.demo.dto.StudentChangedRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.source)) {
        this.source = data().deepCopy(fields()[0].schema(), other.source);
        fieldSetFlags()[0] = true;
      }
      this.sourceBuilder = null;
      if (isValidValue(fields()[1], other.operation)) {
        this.operation = data().deepCopy(fields()[1].schema(), other.operation);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ts_ms)) {
        this.ts_ms = data().deepCopy(fields()[2].schema(), other.ts_ms);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = true;
      }
      this.dataBuilder = null;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public com.kgk.debezium.engine.demo.dto.Source getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder setSource(com.kgk.debezium.engine.demo.dto.Source value) {
      validate(fields()[0], value);
      this.sourceBuilder = null;
      this.source = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'source' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kgk.debezium.engine.demo.dto.Source.Builder getSourceBuilder() {
      if (sourceBuilder == null) {
        if (hasSource()) {
          setSourceBuilder(com.kgk.debezium.engine.demo.dto.Source.newBuilder(source));
        } else {
          setSourceBuilder(com.kgk.debezium.engine.demo.dto.Source.newBuilder());
        }
      }
      return sourceBuilder;
    }

    /**
     * Sets the Builder instance for the 'source' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder setSourceBuilder(com.kgk.debezium.engine.demo.dto.Source.Builder value) {
      clearSource();
      sourceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'source' field has an active Builder instance
     * @return True if the 'source' field has an active Builder instance
     */
    public boolean hasSourceBuilder() {
      return sourceBuilder != null;
    }

    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder clearSource() {
      source = null;
      sourceBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'operation' field.
      * @return The value.
      */
    public java.lang.String getOperation() {
      return operation;
    }


    /**
      * Sets the value of the 'operation' field.
      * @param value The value of 'operation'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder setOperation(java.lang.String value) {
      validate(fields()[1], value);
      this.operation = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'operation' field has been set.
      * @return True if the 'operation' field has been set, false otherwise.
      */
    public boolean hasOperation() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'operation' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder clearOperation() {
      operation = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ts_ms' field.
      * @return The value.
      */
    public java.lang.Long getTsMs() {
      return ts_ms;
    }


    /**
      * Sets the value of the 'ts_ms' field.
      * @param value The value of 'ts_ms'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder setTsMs(java.lang.Long value) {
      validate(fields()[2], value);
      this.ts_ms = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ts_ms' field has been set.
      * @return True if the 'ts_ms' field has been set, false otherwise.
      */
    public boolean hasTsMs() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ts_ms' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder clearTsMs() {
      ts_ms = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public com.kgk.debezium.engine.demo.dto.Student getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder setData(com.kgk.debezium.engine.demo.dto.Student value) {
      validate(fields()[3], value);
      this.dataBuilder = null;
      this.data = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'data' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kgk.debezium.engine.demo.dto.Student.Builder getDataBuilder() {
      if (dataBuilder == null) {
        if (hasData()) {
          setDataBuilder(com.kgk.debezium.engine.demo.dto.Student.newBuilder(data));
        } else {
          setDataBuilder(com.kgk.debezium.engine.demo.dto.Student.newBuilder());
        }
      }
      return dataBuilder;
    }

    /**
     * Sets the Builder instance for the 'data' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder setDataBuilder(com.kgk.debezium.engine.demo.dto.Student.Builder value) {
      clearData();
      dataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'data' field has an active Builder instance
     * @return True if the 'data' field has an active Builder instance
     */
    public boolean hasDataBuilder() {
      return dataBuilder != null;
    }

    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public com.kgk.debezium.engine.demo.dto.StudentChangedRecord.Builder clearData() {
      data = null;
      dataBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StudentChangedRecord build() {
      try {
        StudentChangedRecord record = new StudentChangedRecord();
        if (sourceBuilder != null) {
          try {
            record.source = this.sourceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("source"));
            throw e;
          }
        } else {
          record.source = fieldSetFlags()[0] ? this.source : (com.kgk.debezium.engine.demo.dto.Source) defaultValue(fields()[0]);
        }
        record.operation = fieldSetFlags()[1] ? this.operation : (java.lang.String) defaultValue(fields()[1]);
        record.ts_ms = fieldSetFlags()[2] ? this.ts_ms : (java.lang.Long) defaultValue(fields()[2]);
        if (dataBuilder != null) {
          try {
            record.data = this.dataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("data"));
            throw e;
          }
        } else {
          record.data = fieldSetFlags()[3] ? this.data : (com.kgk.debezium.engine.demo.dto.Student) defaultValue(fields()[3]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StudentChangedRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<StudentChangedRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StudentChangedRecord>
    READER$ = (org.apache.avro.io.DatumReader<StudentChangedRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.source.customEncode(out);

    out.writeString(this.operation);

    if (this.ts_ms == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.ts_ms);
    }

    this.data.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.source == null) {
        this.source = new com.kgk.debezium.engine.demo.dto.Source();
      }
      this.source.customDecode(in);

      this.operation = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.ts_ms = null;
      } else {
        this.ts_ms = in.readLong();
      }

      if (this.data == null) {
        this.data = new com.kgk.debezium.engine.demo.dto.Student();
      }
      this.data.customDecode(in);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.source == null) {
            this.source = new com.kgk.debezium.engine.demo.dto.Source();
          }
          this.source.customDecode(in);
          break;

        case 1:
          this.operation = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ts_ms = null;
          } else {
            this.ts_ms = in.readLong();
          }
          break;

        case 3:
          if (this.data == null) {
            this.data = new com.kgk.debezium.engine.demo.dto.Student();
          }
          this.data.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










